AllCops:
  Include:
    - Rakefile
    - Gemfile
    - '*.gemspec'

# I like the Metrics family in principle, but OAK was built in a
# lower-level style much like C.  The default thresholds for these are
# too tight for the style I chose for OAK.
#
# Moreover, IMO test code is not the place get pedantic about class
# length, method complexity, etc.  One should be encouraged to add
# more tests with minimal friction, not forced to make a hard choice
# between cutting tests or splitting up my test suites.
#
Metrics/ParameterLists:
  Max: 10
Metrics/BlockLength:
  Max: 150
  Exclude:
    - 'test/**/*.rb'
Metrics/ClassLength:
  Max: 400
  Exclude:
    - 'test/**/*.rb'
Metrics/MethodLength:
  Max: 150
  Exclude:
    - 'test/**/*.rb'
Metrics/ModuleLength:
  Max: 1000
  Exclude:
    - 'test/**/*.rb'
Metrics/AbcSize:
  Max: 150
  Exclude:
    - 'test/**/*.rb'
Metrics/BlockNesting:
  Max: 5
Metrics/CyclomaticComplexity:
  Max: 50
Metrics/PerceivedComplexity:
  Max: 25
#
# Normally I am a pedantic adherent to 80-column lines.
#
# Over in test/oak.rb however, there are necessarily a lot of OAK
# strings which are much larger than 80 characters.
#
# I have decided that disablement in .rubocop.yml is less disruptive
# than repeate use of inline rubocop: comments.
#
Metrics/LineLength:
  Exclude:
    - 'test/**/*.rb'
Naming/UncommunicativeMethodParamName:
  Enabled: false

# I put extra spaces in a lot of expressions for a lot of different
# reasons, including especially readability.
#
# I reject these cops.
#
Layout:
  Enabled: false

# As a group, the Style cops are bewilderingly opiniated.
#
# In some cases IMO they are harmful e.g. Style/TernaryParentheses.
#
# I reject these cops.
#
Style:
  Enabled: false
