sudo: true
language: ruby
before_install:
  - gem install bundler -v 1.16.1
rvm:
  - 2.1.6
  - 2.2.9
  - 2.4.3
  - 2.5.0
script:
  #
  # Run several tests in parallel, and be happy if they are all happy.
  #
  # If any fail, rerun serially so we get clean output from the ones
  # which failed.
  #
  - make test -j 3 || make test
